name: celeri
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pyproj
  - pandas
  - jupyterlab
  - ipympl
  - meshio
  - pytest
  - tqdm
  - h5py
  - colorcet
  - lxml
  - rich
  - dill
  - cvxpy
  - cvxopt
  - compilers
  - fortran-compiler
  - cutde
  - ghostscript
  - spherical-geometry
  - loguru
  - pygmt
  - gmsh
  - polars
  - seaborn
  - pip
  - pip:
      - okada_wrapper
